### ISSUE TITLE
自行构建报错

### ISSUE THREAD

**Issue by loonghfut** [imzlh/alist-ui-vlist#1]
![1730085683074](https://github.com/user-attachments/assets/d8f20ced-1b72-4791-baa7-f254cda1568d)

**Comment by imzlh** [comment]
试试看新版本可不可以编译，我这里可以

<img width="622" alt="image" src="https://github.com/user-attachments/assets/18df2140-d00a-4c9a-a015-255ea3bc0c45">

**Comment by loonghfut** [comment]
好的，我待会试试
